name: py35
dependencies:
- numpy==1.16.1
- astropy==3.0.3
- python>=3.5
- bokeh==1.0.4
- astroquery==0.3.9
- scipy==1.1.0
- pandas==0.23.4
- lmfit==0.9.12
- pip:
  - svo_filters==0.2.16
  - dustmaps==1.0