name: py35
dependencies:
- numpy==1.18.1
- astropy==4.0
- python>=3.5.3
- bokeh==1.4.0
- astroquery==0.4.1
- scipy==1.4.1
- pandas==0.23.4
- selenium==2.49.2
- pip:
  - svo_filters==0.2.19
  - dustmaps==1.0