name: sedkit
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - numpy>=1.18.1
  - astropy>=4.0
  - python>=3.6.8
  - bokeh>=1.4.0
  - astroquery>=0.4.1
  - scipy>=1.4.1
  - pandas>=0.23.4
  - pip>=20.3.3
  - selenium>=2.49.2
  - pytest>=6.2.1
  - jupyter>=1.0.0
  - ipython>=7.12.0
  - pip:
    - svo-filters==0.3.0
    - dustmaps==1.0.4
    - numpydoc==0.8.0
    - emcee>=3.0.2