name: sedkit
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - numpy=1.18.1
  - astropy=4.0
  - python=3.6.8
  - bokeh=1.4.0
  - astroquery=0.4.1
  - scipy=1.2.1
  - pandas=0.23.4
  - selenium=2.49.2
  - pytest=5.4.3
  - jupyter=1.0.0
  - ipython=7.12.0
  - pip:
    - svo-filters==0.2.19
    - dustmaps==1.0.4
    - astroquery==0.4.1
    - numpydoc==0.8.0