# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2017-05-23 23:27:59.131538
from __future__ import unicode_literals
import datetime

version = "1.3.1"
githash = "70b09af7e4f6b8a4e409412a913ff2adb05c12b7"


major = 1
minor = 3
bugfix = 1

release = True
timestamp = datetime.datetime(2017, 5, 23, 23, 27, 59, 131538)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
