name: sedkit-3.8
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - numpy>=1.20.1
  - astropy>=4.3.1
  - astroquery>=0.4.2
  - python>=3.8
  - bokeh>=2.3.0
  - scipy>=1.6.0
  - pandas>=1.2.4
  - pickle5>=0.0.11
  - pip>=21.0.1
  - selenium>=3.141.0
  - sphinx>=3.5.1
  - sphinx-automodapi>=0.13
  - pytest>=6.2.1
  - pygments>=2.8.0
  - jupyter>=1.0.0
  - ipython>=7.21.0
  - pip:
    - svo-filters==0.4.1
    - dustmaps==1.0.8
    - numpydoc==0.8.0
    - emcee>=3.0.2