name: sedkit-3.10

channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- pip
- python=3.10
- pip:
  - astropy>=5.3.1
  - astroquery>=0.4.6
  - bokeh>=3.2.1
  - dill>=0.3.4
  - dustmaps>=1.0.9
  - emcee>=3.1.1
  - ipython==8.2.0
  - jupyter==1.0.0
  - numpy>=1.25.1
  - pandas>=1.3.5
  - PyQt5>=5.15.6
  - pytest==7.1.1
  - sphinx==4.5.0
  - scipy>=1.8.0
  - svo-filters>=0.4.4
