name: sedkit-3.8
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - numpy>=1.18.1
  - astropy>=4.3.1
  - astroquery>=0.4.2
  - dill>=0.3.4
  - python>=3.8
  - bokeh>=1.4.0
  - scipy>=1.4.1
  - pandas>=0.23.4
  - pip>=20.3.3
  - selenium>=2.49.2
  - sphinx>=3.4.3
  - sphinx-automodapi>=0.13
  - pytest==6.2.1
  - pygments>=2.7.4
  - tqdm>=4.62.3
  - jupyter>=1.0.0
  - ipython>=7.12.0
  - pip:
    - svo-filters==0.4.1
    - dustmaps==1.0.4
    - numpydoc>=1.1.0
    - emcee>=3.0.2
