name: sedkit-3.8
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - numpy>=1.18
  - astropy>=4.1
  - astroquery>=0.4.2
  - dill>=0.3.4
  - python>=3.8, <3.9
  - bokeh>=2.4.2
  - scipy>=1.2
  - pandas>=1.2
  - pickle5>=0.0.12
  - pip>=22.0.4
  - selenium>=4.1.0
  - sphinx>=4.5.0
  - sphinx-automodapi>=0.14.1
  - pytest>=6.2
  - pygments>=2.11.2
  - jupyter>=1.0.0
  - ipython>=7.23.1
  - pip:
    - svo-filters==0.4.1
    - dustmaps>=1.0.8
    - emcee>=3.1.1
