name: sedkit Workflow

on: [push]

jobs:
  build-linux:
    name: Python - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file env/environment-${{ matrix.python-version }}.yml --name sedkit-${{ matrix.python-version }}
      env:
        PYTHONVERSION: ${{ matrix.python-version }}
    - name: Test with pytest
      run: |
        conda run -n sedkit-${{ matrix.python-version }} pytest
